import NavBar from "./components/NavBar";

import "./global.css";
import { Roboto } from "next/font/google";
export const metadata = {
  title: "HomePage NextJS",
  description: "Generated by AndresRiscanevo",
  keywords: "store,online,ecommerce",
};
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="container mx-auto h-[calc(100hv-8rem)] flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
